### ISSUE TITLE
[Feature Request] Import address by seed phrase

### ISSUE THREAD

**Issue by satindergrewal** [VerusCoin/VerusCoin#307]
I'm not sure if it's already in command line or in plan, but this is my feature request:

Importing of address generated through [BIP39 mnemonic seeds](https://github.com/bitcoin/bips/tree/master/bip-0039).

Example command can look like this:

```shell
komodo-cli -ac_name=VRSC importbyseed "your strong seed phrase goes here"
```

Which behaves exactly like `importprivkey` command, and outputs the imported address.

The idea is to extend the possibility of using a seed phrase to import the address to the wallet.
And using this seed phrase generated address as primary address for VerusID.

**Comment by Asherda** [comment]
Closed by https://github.com/VerusCoin/VerusCoin/commit/5efcf33bdff91768a8d42e6469b79729c02cd39d
