### ISSUE TITLE
Field `address` exists twice in raw transaction JSON return object

### ISSUE THREAD

**Issue by jorian** [VerusCoin/VerusCoin#432]
See: https://github.com/VerusCoin/VerusCoin/blob/9e8227b1b7018eb507338912aec6da017c2a1971/src/rpc/rawtransaction.cpp#L180

Whenever a transaction is queried using `getrawtransaction` and setting the verbose parameter to true, a JSON object of the transaction is returned.

In case this transaction is the spending of a staked coinbase transaction, the `address` field appears twice in the response, breaking the rule of having only unique keys in a JSON object.

On current testnet, this is reproducable by doing the following query:

`verus-cli getrawtransaction 1a8eaedf117d8851fb7d9639f3524a7822168099fff3ba5ce369b1d6acba19ed 1`

The response is then:

![image](https://user-images.githubusercontent.com/10341677/175109998-1e870444-a0f0-4b2c-b0ed-4b33e8c1e1c5.png)

This issue does not appear in normal PoW coinbases or other types of transactions in the vin array.

**Comment by jorian** [comment]
After some more testing, I found out that it also happens when a standard P2PKH transaction is queried using the `getrawtransaction` call:

`./verus -chain=vrsctest getrawtransaction b8e5b0d49c9e3ca58d3b035cb3239ff5e5fb81c3f3e8c25dcefd509d1d5b8893 1`

![image](https://user-images.githubusercontent.com/10341677/175255352-68c7e8bc-f8b8-4fbb-97c9-ea07241bb0a3.png)

[View transaction on explorer](https://testex.verus.io/tx/b8e5b0d49c9e3ca58d3b035cb3239ff5e5fb81c3f3e8c25dcefd509d1d5b8893)

**Comment by miketout** [comment]
This is fixed in https://github.com/miketout/VerusCoin/commit/c5c41ffa3330a971ca57ef6310a0085c576fed04
Please close when it is pulled into main and confirmed.

**Comment by jorian** [comment]
Confirmed fixed!
