### ISSUE TITLE
Mac OS command line VerusCoin wallet install issue

### ISSUE THREAD

**Issue by shaman-narayanasamy** [VerusCoin/VerusCoin#77]
I am attempting to install the command line version of the VerusCoin mining wallets. 

I run the following `$ ./fetch-params.sh`

This is the output I receive:
``` 
   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:04 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:09 --:--:--     0
curl: (35) LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to z.cash:443 
```
### Can you reliably reproduce the issue?
Have yet to reproduce on other machines.

#### If so, please list the steps to reproduce below:
1. Download 
2. Decompress (untar/gunzip)
3. See above

### Machine specs:
- OS name + version: MacOS High Sierra 10.13.3 (17D47)
- CPU: 2,9 GHz Intel Core i7
- RAM: 16 GB 2133 MHz LPDDR3
- Disk size: 1TB
- Disk Type (HD/SDD): SSD
- Linux kernel version (uname -a): Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64 x86_64
- Compiler version (gcc -version): 
```
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 9.0.0 (clang-900.0.39.2)
Target: x86_64-apple-darwin17.4.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

**Comment by ca333** [comment]
can you please check your curl version? I see your sys is using libressl - do you have openssl installed? I tried to reproduce but without success - i am using curl w/ openssl.

**Comment by Asherda** [comment]
Issue has been addressed. The fetch-params script will work on Mac and Linux systems
